accelerator_config: ''
adafactor: false
adam_beta1: '0.9'
adam_beta2: '0.999'
adam_epsilon: 1e-08
auto_find_batch_size: false
batch_eval_metrics: false
bf16: false
bf16_full_eval: false
cache_dir: ''
config_name: ''
data_seed: ''
dataloader_drop_last: 'True'
dataloader_num_workers: 0
dataloader_persistent_workers: false
dataloader_pin_memory: true
dataloader_prefetch_factor: ''
ddp_backend: ''
ddp_broadcast_buffers: ''
ddp_bucket_cap_mb: ''
ddp_find_unused_parameters: ''
ddp_timeout: 1800
debug: ''
deepspeed: ''
disable_tqdm: ''
dispatch_batches: ''
do_eval: false
do_predict: false
do_train: false
eval_accumulation_steps: ''
eval_delay: 0
eval_do_concat_batches: true
eval_on_start: false
eval_steps: ''
eval_strategy: 'no'
evaluation_strategy: ''
fix_position_embedding: false
fp16: true
fp16_backend: auto
fp16_full_eval: false
fp16_opt_level: O1
fsdp: ''
fsdp_config: ''
fsdp_min_num_params: 0
fsdp_transformer_layer_cls_to_wrap: ''
full_determinism: false
gradient_accumulation_steps: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs: ''
greater_is_better: ''
group_by_length: false
half_precision_backend: auto
hub_always_push: false
hub_model_id: ''
hub_private_repo: false
hub_strategy: every_save
hub_token: ''
ignore_data_skip: false
include_inputs_for_metrics: false
include_num_input_tokens_seen: false
include_tokens_per_second: false
jit_mode_eval: false
label_names: ''
label_smoothing_factor: '0.0'
learning_rate: 1.0e-05
length_column_name: length
load_best_model_at_end: false
local_rank: -1
log_level: passive
log_level_replica: warning
log_on_each_node: true
logging_dir: ''
logging_first_step: false
logging_nan_inf_filter: true
logging_steps: 10
logging_strategy: steps
lr_scheduler_kwargs: '{}'
lr_scheduler_type: linear
max_example_num_per_dataset: 100000000
max_grad_norm: '1.0'
max_steps: '-1'
metric_for_best_model: ''
model_name: 'BAAI/bge-m3'
mp_parameters: ''
neftune_noise_alpha: ''
negatives_cross_device: true
no_cuda: false
no_dataloader_pin_memory: false
no_eval_do_concat_batches: false
no_log_on_each_node: false
no_logging_nan_inf_filter: false
no_normlized: false
no_remove_unused_columns: false
no_save_safetensors: false
no_skip_memory_metrics: false
no_use_inbatch_neg: false
normlized: 'True'
num_train_epochs: 5
optim: adamw_torch
optim_args: ''
optim_target_modules: ''
output_dir: ''
overwrite_output_dir: false
passage_instruction_for_retrieval: ''
passage_max_len: 256
past_index: -1
per_device_eval_batch_size: 8
per_device_train_batch_size: 1
per_gpu_eval_batch_size: ''
per_gpu_train_batch_size: ''
prediction_loss_only: false
push_to_hub: false
push_to_hub_model_id: ''
push_to_hub_organization: ''
push_to_hub_token: ''
query_instruction_for_retrieval: ''
query_max_len: 64
ray_scope: last
remove_unused_columns: true
report_to: ''
restore_callback_states_from_checkpoint: false
resume_from_checkpoint: ''
run_name: ''
save_on_each_node: false
save_only_model: false
save_safetensors: true
save_steps: 1000
save_strategy: steps
save_total_limit: ''
seed: 42
sentence_pooling_method: cls
skip_memory_metrics: true
split_batches: ''
temperature: 0.02
tf32: ''
tokenizer_name: ''
torch_compile: false
torch_compile_backend: ''
torch_compile_mode: ''
torchdynamo: ''
tpu_metrics_debug: false
tpu_num_cores: ''
train_data: 
train_group_size: 2
use_cpu: false
use_inbatch_neg: false
use_ipex: false
use_legacy_prediction_loop: false
use_mps_device: false
warmup_ratio: '0.0'
warmup_steps: '0'
weight_decay: '0.0'
