embedding: dkubex 
dkubex:
  embedding_url: http://xxx.xxx.xxx.xxx:xxxxx/xxx/xxx/                    # Provide serving url of local embedding model deployment
  embedding_key: eyJhbGc**************V5s3b0                              # Provide service token of local embedding model deployment
  batch_size: 10
reader:
  - file
file:
  inputs:
    loader_args:
      input_dir: /home/<username>/contract-nli                            # Replace <username> with your DKubeX username
      recursive: true 
      exclude_hidden: true 
      raise_on_error: true 
splitter: sentence_text_splitter
sentence_text_splitter:
  chunk_size: 256
  chunk_overlap: 0
metadata:
  - default
adjacent_chunks: true
mlflow:
  experiment: demo-ingestion-quickstart
